# Generated by Django 4.2.7 on 2024-05-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_categories_reviews_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
