# Generated by Django 4.2.7 on 2024-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='catrgory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
