# Generated by Django 4.2.7 on 2024-05-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_product_category_product_catrgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catrgory',
            new_name='category',
        ),
    ]
