# Generated by Django 4.2.7 on 2024-05-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_catrgory_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
