# Generated by Django 4.2.7 on 2024-05-10 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_cart_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Products',
            new_name='Cart_Product',
        ),
    ]
