# Generated by Django 4.2.7 on 2024-05-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_cart_products_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
