# Generated by Django 4.2.7 on 2024-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand', models.ManyToManyField(to='base.brand')),
            ],
        ),
    ]
