# Generated by Django 4.2.7 on 2024-05-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='object_id',
        ),
    ]
