# Generated by Django 4.2.7 on 2024-05-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_storage_content_type_remove_storage_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='storage',
            field=models.ManyToManyField(to='base.storage'),
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
