# Generated by Django 4.2.7 on 2024-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_brand_storage_delete_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='storage',
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(to='base.storage'),
        ),
    ]
