# Generated by Django 4.2.7 on 2024-05-20 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_alter_product_color_alter_product_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('prouduct_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('product_color', models.CharField(blank=True, max_length=100, null=True)),
                ('product_storage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart_Product',
        ),
    ]
