# Generated by Django 4.2.7 on 2024-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_cart_product_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='selected_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart_product',
            name='selected_storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
