# Generated by Django 4.2.7 on 2024-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
