# Generated by Django 4.2.7 on 2024-05-28 07:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_orderitem_selected_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subImages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), blank=True, null=True, size=8),
        ),
    ]
