# Generated by Django 4.2.7 on 2024-05-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_product_subimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subImages',
            new_name='sub_images',
        ),
    ]
